helloworld:
	nasm -f elf64 helloworld.asm && ld -o helloworld helloworld.o

registers:
	nasm -f elf64 registers.asm && ld -o registers registers.o

read:
	nasm -f elf64 read.asm && ld -o read read.o

addressing:
	nasm -f elf64 addressing.asm && ld -o addressing addressing.o
