helloworld:
	nasm -f elf64 helloworld.asm && ld -o helloworld helloworld.o

registers:
	nasm -f elf64 registers.asm && ld -o registers registers.o

read:
	nasm -f elf64 read.asm && ld -o read read.o

addressing:
	nasm -f elf64 addressing.asm && ld -o addressing addressing.o

const_equ:
	nasm -f elf64 const_equ.asm && ld -o const_equ const_equ.o

add:
	nasm -f elf64 add.asm && ld -o add add.o

mul:
	nasm -f elf64 mul.asm && ld -o mul mul.o

and:
	nasm -f elf64 and.asm && ld -o and and.o

or:
	nasm -f elf64 or.asm && ld -o or or.o

conditions:
	nasm -f elf64 conditions.asm && ld -o conditions conditions.o

loops:
	nasm -f elf64 loops.asm && ld -o loops loops.o

numbers:
	nasm -f elf numbers.asm && ld -m elf_i386 -o numbers numbers.o

arrays:
	nasm -f elf64 arrays.asm && ld -o arrays arrays.o

procedures:
	nasm -f elf64 procedures.asm && ld -o procedures procedures.o

stack:
	nasm -f elf64 stack.asm && ld -o stack stack.o

fact:
	nasm -f elf64 fact.asm && ld -o fact fact.o

macros:
	nasm -f elf64 macros.asm && ld -o macros macros.o

file:
	nasm -f elf64 file.asm && ld -o file file.o

memory:
	nasm -f elf64 memory.asm && ld -o memory memory.o
